# Site settings

  
    
      
    
title:              "Joël Lesenne"
description:        "Joël Lesenne is a designer and developer who lives to Lyon (France)"

  
    
      
    
  author:             "Joël Lesenne"
url:                "https://joellesenne.github.io"
baseurl:            ""
lang:               "en"
#relative_permalinks: false
#permalink:          pretty

# Open Card Twitter
twitter:          "@joellesenne"

# My site Web
mysite:
  name:           "Joël Lesenne"
  url:            "https://joellesenne.xyz"

# Site repository
repository:
  title:            "Github"
  name:             "joellesenne.github.io"
  url:              "https://joellesenne.github.io"
  repo:             "https://github.com/joellesenne/joellesenne.github.io"
  branch:           "master"

# Static-site
framework:
  name:             Jekyll
  url:              https://jekyllrb.com/

# Build settings
timezone:           Europe/Paris
markdown:           kramdown

# Plugins
plugins:
  - jekyll-sitemap

# plunings Settings
sitemap:
  lastmod:          2018-02-12
  priority:         0.7
  changefreq:       'monthly'
  exclude:          'yes'

# Handling reading
include:            ["_pages"]
exclude:            ["CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "LICENCE", "README.md", "Gemfile", "Gemfile.lock"]
